// React/shopping-cart/src/components/login/Login.jsx
import React, { Component } from "react";

class Login extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {
    return (
      <div className="row">
        <div className="col-md-4 offset-md-4">
          <div className="guest-form-card card">
            <div className="card-header text-center">
              <h2>Login Here</h2>
            </div>

            <div className="card-body">
              <form>
                <div className="form-group">
                  <label for="username">Username</label>
                  <input id="username" className="form-control" />
                  <span className="invalid-feedback">
                    Username can't be blank.
                  </span>
                </div>

                <div className="form-group">
                  <label for="password">Password</label>
                  <input
                    type="password"
                    id="password"
                    name="password"
                    className="form-control"
                  />
                  <span className="invalid-feedback">
                    Password can't be blank.
                  </span>
                </div>

                <div className="form-group">
                  <input type="checkbox" id="remember" name="remember" />
                  <label className="ml-1" for="remember">
                    Remember Me
                  </label>
                </div>

                <button className="btn btn-primary btn-block">Login</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Login;

// Angular/Shopping-cart/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor() { }
  model: any = {}
  ngOnInit(): void {
  }

  login(){

  }
}

<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="guest-form-card card">

      <div class="card-header text-center">
        <h2>Login Here</h2>
      </div>

      <div class="card-body">
        <form #loginform="ngForm" (ngSubmit)="login()">
          <div class="form-group">
            <label for="username">Username</label>
            <input id="username" class="form-control" [ngClass]="{ 'is-invalid': username.touched && username.invalid }" name="username" #username="ngModel" [(ngModel)]="model.username" required>
            <span class="invalid-feedback">Username can't be blank.</span>
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" class="form-control" [ngClass]="{ 'is-invalid': password.touched && password.invalid }" #password="ngModel" [(ngModel)]="model.password" required>
            <span class="invalid-feedback">Password can't be blank.</span>
          </div>

          <div class="form-group">
            <input type="checkbox" id="remember" name="remember" #remember="ngModel" [(ngModel)]="model.remember">
            <label class="ml-1" for="remember">Remember Me</label>
          </div>

          <button class="btn btn-primary btn-block">Login</button>
        </form>
      </div>
    </div>
  </div>
</div>
