// Angular/Shopping-cart/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Shopping-cart';
}

<app-nav></app-nav>
<div class="container">
<div class="row">
  <div class="col">
    <router-outlet></router-outlet>
  </div>
</div>
<div class="row">
  <div class="col">
    <app-footer></app-footer>
  </div>
</div>
</div>

// React/shopping-cart/src/App.js
import './App.css';

import React from 'react';

import Nav from './components/shared/nav/Nav.jsx'
import Footer from './components/shared/footer/Footer.jsx'
import ShoppingCart from './components/shopping-cart/ShoppingCart.jsx'
import { Redirect, Route, Router, Switch } from 'react-router-dom';
import Login from './components/login/Login';
import Register from './components/register/Register';
function App() {
  return (
   <div className="container">
      <div className="row">
        <div className='col'>
            <Nav/>
       </div>
       <div className="row">
       <div className='col'>
          
       <Switch>
   
                        <Route path="/" exact render={() => <Redirect to="/ShoppingCart" />} />
                        <Route path="/login" component={Login} />
                        <Route path="/register" component={Register} />
                        <Route path="/ShoppingCart" exact component={ShoppingCart} />
                        
                        {/* <Route path="/**" component={PageNotFound} /> */}
                    </Switch>
            
          </div>
       </div>
       <div className="row">
       <div className='col'>
          <Footer/>
          </div>
       </div>
      
         
      </div>
   </div>
  );
}

export default App;
