// Angular/Shopping-cart/src/app/components/shopping-cart/cart/cart-item/cart-item.component.ts
import { Cart } from 'src/app/models/cart';
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-cart-item',
  templateUrl: './cart-item.component.html',
  styleUrls: ['./cart-item.component.css']
})
export class CartItemComponent implements OnInit {

  @Input() cartItem!:Cart;
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="card-item">
  <span>{{cartItem.productName}}</span> X <span>{{cartItem.qty}}</span>: <strong>{{cartItem.qty*cartItem.price | currency:'INR'}}</strong>
</div>

// React/shopping-cart/src/components/shopping-cart/cart/cart-item/CartItem.jsx
import React, { Component } from "react";

class CartItem extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    const { product } = this.props;
    return (
      <div class="card-item">
        <span>{product.productName}</span> X <span>{product.qty}</span>:
        <strong>{product.price * product.qty}</strong>
      </div>
    );
  }
}

export default CartItem;
