// React/shopping-cart/src/components/register/Register.jsx
import React, { Component } from "react";

class Register extends Component {
  state = {};
  render() {
    return (
      <div className="row">
        <div className="col-md-4 offset-md-4">
          <div className="guest-form-card card">
            <div className="card-header text-center">
              <h2>Register Here</h2>
            </div>

            <div className="card-body">
              <form>
                <div className="form-group">
                  <label for="name">Name</label>
                  <input id="name" className="form-control" name="name" />
                  <span className="invalid-feedback">Name can't be blank.</span>
                </div>
                <div className="form-group">
                  <label for="email">Email</label>
                  <input
                    id="email"
                    className="form-control"
                    name="email"
                    formControlName="email"
                  />
                </div>
                <div className="form-group">
                  <label for="username">Username</label>
                  <input
                    id="username"
                    className="form-control"
                    name="username"
                    formControlName="userName"
                  />
                </div>

                <div className="form-group">
                  <label for="password">Password</label>
                  <input
                    type="password"
                    id="password"
                    name="password"
                    className="form-control"
                    formControlName="password"
                  />
                </div>
                <div className="form-group">
                  <label for="confirmPassword">Re-Enter Password</label>
                  <input
                    type="password"
                    id="confirmPassword"
                    name="confirmPassword"
                    className="form-control"
                  />
                  <span className="invalid-feedback">
                    Password should match.
                  </span>
                </div>

                <button className="btn btn-primary btn-block">Register</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Register;

// Angular/Shopping-cart/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import {  FormBuilder,  FormGroup,  Validators } from '@angular/forms';

// export function ConfirmedValidator(controlName: string, matchingControlName: string){
//   return (formGroup: FormGroup) => {
//       const control = formGroup.controls[controlName];
//       const matchingControl = formGroup.controls[matchingControlName];
//       if (matchingControl.errors && !matchingControl.errors.confirmedValidator) {
//           return;
//       }
//       if (control.value !== matchingControl.value) {
//           matchingControl.setErrors({ confirmedValidator: true });
//       } else {
//           matchingControl.setErrors(null);
//       }
//   }
// }

function ConfirmedValidator(form:any) {
  const password = form.get('password')
  const confirmPassword = form.get('confirmPassword')

  if(password.value !== confirmPassword.value) {
    confirmPassword.setErrors({ passwordsMatch: true })
  } else {
    confirmPassword.setErrors(null)
  }

  return null
}

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  registerForm : any  ;
  constructor(private bldr:FormBuilder) {

    this.registerForm=bldr.group({
      name:['',Validators.required],
      userName:['',Validators.required],
      email:['',[Validators.required,Validators.email]],
      password:['',Validators.required],
      confirmPassword:['', [Validators.required]]
    },{
      Validators: ConfirmedValidator
    }
    );

   }

  ngOnInit(): void {


  }

  register(){
    console.log(this.registerForm.value)
  }
}

<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="guest-form-card card">

      <div class="card-header text-center">
        <h2>Register Here</h2>
      </div>

      <div class="card-body">
        <form [formGroup]="registerForm" (ngSubmit)="register()">
          <div class="form-group">
            <label for="name">Name</label>
            <input id="name" class="form-control"  name="name"
            formControlName="name"
            [ngClass]="{'is-invalid': registerForm.get('name').touched &&  registerForm.get('name').invalid}"
            >
            <span class="invalid-feedback">Name can't be blank.</span>
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input id="email" class="form-control"  name="email"  formControlName="email"
            [ngClass]="{'is-invalid': registerForm.get('email').touched &&  registerForm.get('email').invalid}">
            <span *ngIf="registerForm.get('email').hasError('required')" class="invalid-feedback">email can't be blank.</span>
            <span *ngIf="registerForm.get('email').hasError('email')" class="invalid-feedback">Should be valid email</span>
          </div>
          <div class="form-group">
            <label for="username">Username</label>
            <input id="username" class="form-control"  name="username"
             formControlName="userName"
             [ngClass]="{'is-invalid': registerForm.get('userName').touched &&  registerForm.get('userName').invalid}">
            <span class="invalid-feedback">Username can't be blank.</span>
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" class="form-control"
            formControlName="password"
            [ngClass]="{'is-invalid': registerForm.get('password').touched &&  registerForm.get('password').invalid}">

            <span class="invalid-feedback">Password can't be blank.</span>
          </div>
          <div class="form-group">
            <label for="confirmPassword">Re-Enter Password</label>
            <input type="password" id="confirmPassword" name="confirmPassword" class="form-control"
             [ngClass]="{ 'is-invalid': registerForm.get('confirmPassword').touched && registerForm.get('confirmPassword').invalid  }"
              formControlName="confirmPassword">
             <span class="invalid-feedback">Password should match.</span>
          </div>
{{registerForm.get('confirmPassword').hasError('confirmedValidator')}}
          <button class="btn btn-primary btn-block" [disabled]="registerForm.invalid" >Register</button>
        </form>
      </div>
    </div>
  </div>
</div>
