// React/shopping-cart/src/components/shopping-cart/product-list/product-item/ProductItem.jsx
import React, { Component } from "react";
import { Card, CardImg, CardText, CardBody, CardTitle } from "reactstrap";
import { connect } from "react-redux";

import NumberFormat from "react-number-format";
import { addToCart } from "../../../../service/CartService";

class ProductItem extends Component {
  handleAddToCart = (e) => {
    e.preventDefault();

    const { product } = this.props;
    let cartItem = {
      productId: product.id,
      productName: product.name,
      price: product.price,
      qty: 1,
    };
    console.log(this.props);
    this.props.addCart(cartItem);
  };

  render() {
    const { product } = this.props;

    return (
      <div>
        <Card>
          <CardImg
            top
            width="100%"
            src={product.imageUrl}
            alt="Card image cap"
          />
          <CardBody>
            <CardTitle tag="h5">{product.name}</CardTitle>
            <CardText tag="h5">
              <strong>
                <NumberFormat
                  value={product.price}
                  displayType={"text"}
                  thousandSeparator={true}
                  prefix={"$"}
                />
              </strong>
            </CardText>
            <CardText>{product.description}</CardText>
            <div className="d-flex justify-content-between align-items-center">
              <div className="btn-group">
                <button
                  type="button"
                  className="btn btn-sm btn-primary product-btn"
                  onClick={this.handleAddToCart}
                >
                  Add to Cart
                </button>
                <button
                  type="button"
                  className="btn btn-sm btn-outline-secondary product-btn"
                >
                  View Details
                </button>
              </div>
            </div>
          </CardBody>
        </Card>
      </div>
    );
  }
}
const mapStateToProps = (state) => {
  return {
    cartData: state.cart,
  };
};
const mapDispatchToProps = (dispatch) => {
  //store.dispatch
  return {
    addCart: (data) => {
      dispatch(addToCart(data));
    },
  };
};

// export default connect(null, { AddCartAction })(ProductItem);
export default connect(mapStateToProps, mapDispatchToProps)(ProductItem);

// Angular/Shopping-cart/src/app/components/shopping-cart/product-list/product-item/product-item.component.ts
import { WishlistService } from './../../../../services/wishlist.service';
import { CartService } from './../../../../services/cart.service';
import { MessengerService } from './../../../../services/messenger.service';
import { Product } from './../../../../models/product';
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.css']
})
export class ProductItemComponent implements OnInit {

  @Input() productItem!:Product
  constructor(private msg:MessengerService,
    private cartService:CartService, private wishlist:WishlistService) {

   }

  wishlistAdded:boolean=false;
  ngOnInit(): void {
     this.wishlist.getWishlist().subscribe((item)=>{
      this.wishlistAdded=item.indexOf(this.productItem.id)>0
   });
  }

  handleAddToCart(){
    this.cartService.addProductToCart(
    {productId: this.productItem.id,
    productName:this.productItem.name,
    price:this.productItem.price,qty:1}).subscribe(()=>{})
    this.msg.sendMsg(this.productItem);
  }

  handleAddToWishlist(){
      this.wishlist.addToWishlist(this.productItem.id).subscribe(()=>{
        this.wishlistAdded=true;
      });
  }
  handleRemoveToWishlist(){
    this.wishlist.removeWishlist(this.productItem.id).subscribe(()=>{
      this.wishlistAdded=false;
    });
  }

}

<div class="card shadow-sm">

 <img class="bd-placeholder-img card-img-top" width="100%"
  [src]="productItem.imageUrl"/>


  <div class="card-body">
    <p class="card-text">
      <strong>{{productItem.price |currency:'INR'}}</strong>
      <i class="far fa-heart float-md-end " *ngIf="!wishlistAdded" (click)="handleAddToWishlist()"></i>
      <i class="fas fa-heart float-md-end "  *ngIf="wishlistAdded" (click)="handleRemoveToWishlist()" ></i>
    </p>
    <p class="card-text">
      <strong>{{productItem.name}}</strong>
    </p>
    <p class="card-text">  {{productItem.description | slice: 0:50}}...</p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <button type="button"
        class="btn btn-sm btn-primary product-btn"
        (click)="handleAddToCart()">Add to Cart</button>
        <button type="button" class="btn btn-sm btn-outline-secondary product-btn">View Details</button>
      </div>

    </div>
  </div>
</div>
