// Angular/Shopping-cart/src/app/components/shopping-cart/cart/cart.component.ts
import { Cart } from './../../../models/cart';
import { CartService } from './../../../services/cart.service';
import { Product } from './../../../models/product';
import { MessengerService } from './../../../services/messenger.service';
import { Component, OnInit } from '@angular/core';
import { isNgTemplate } from '@angular/compiler';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {
  cartItems:Cart[]=[];
  cartTotal:number=0
  constructor(private msg: MessengerService,private cartService : CartService) { }

  ngOnInit(): void {
    this.msg.getMsg().subscribe((product :any) =>{
      this.getCartItems();
    });
    this.getCartItems();
  }

  getCartItems(){
    this.cartService.getCartItems().subscribe((cart :Cart[]) =>{
      this.addProductToCart(cart);
      this.getCartTotal();
    });
  }
  addProductToCart(cartList:Cart[]){
    this.cartItems=[];
    for(let cart in cartList){

    let itemExists= false;
    for(let item in this.cartItems){
      if(this.cartItems[item].productId=== cartList[cart].productId){
        this.cartItems[item].qty++;
        itemExists=true;
        break;
      }
    }

    if(!itemExists){
      this.cartItems.push({
        productId:cartList[cart].productId,
        productName:cartList[cart].productName,
        price:cartList[cart].price,
        qty:1
      })
    }
  }
}
  getCartTotal(){
    this.cartItems.forEach(item=>{
      this.cartTotal += (item.price*item.qty)
    });

  }
}

<div class="alert alert-info" *ngIf="cartItems.length===0">
  Empty cart.
</div>
<ul class="list-group" *ngIf="cartItems.length>0">
  <li class="list-group-item" *ngFor="let item of cartItems">
    <app-cart-item [cartItem]="item"></app-cart-item>
  </li>
  <li class="list-group-item active">
    Total : <strong>{{cartTotal | currency:'INR'}}</strong>
  </li>
</ul>

// React/shopping-cart/src/components/shopping-cart/cart/Cart.jsx
import { getByPlaceholderText } from "@testing-library/dom";
import React, { Component, useEffect } from "react";
import { connect } from "react-redux";
import CartItem from "./cart-item/CartItem";
import { getCartList } from "../../../service/CartService";

function Cart({ cartData, getCartList }) {
  useEffect(() => {
    getCartList();
  }, []);

  return (
    <ul className="list-group">
      {manipulateCart(cartData.cart).map((item) => (
        <li className="list-group-item">
          <CartItem key={item.id} product={item} />
        </li>
      ))}

      <li className="list-group-item active">
        Total : <strong>{getCartTotal(cartData)}</strong>
      </li>
    </ul>
  );
}

const manipulateCart = (products) => {
  var cartItems = [];
  for (let prds in products) {
    let itemExists = false;
    for (let item in cartItems) {
      if (cartItems[item].productId === products[prds].productId) {
        cartItems[item].qty++;
        itemExists = true;
        break;
      }
    }

    if (!itemExists) {
      cartItems.push({
        productId: products[prds].productId,
        productName: products[prds].productName,
        price: products[prds].price,
        qty: 1,
      });
    }
  }
  return cartItems;
};

const getCartTotal = (cartData) => {
  var total = 0;
  cartData.cart.forEach((item) => {
    total += item.price * item.qty;
  });
  return total;
};

const mapStateToProps = (state) => {
  return {
    cartData: state.cart,
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    getCartList: () => dispatch(getCartList()),
  };
};
export default connect(mapStateToProps, mapDispatchToProps)(Cart);

// class Cart extends Component {
//   componentDidMount() {
//     getCartList().then((result) => this.manipulateCart(result.cart));
//   }

//   getCartTotal() {
//     const { cartData2 } = this.state;
//     var total = 0;
//     cartData2.forEach((item) => {
//       total += item.price * item.qty;
//     });
//   }

//   render() {
//     const { cartData2 } = this.state;
//     return (
//       <ul class="list-group">
//         {cartData2.map((item) => (
//           <li class="list-group-item">
//             <CartItem key={item.id} product={item} />
//           </li>
//         ))}

//         <li class="list-group-item active">
//           Total : <strong>{this.getCartTotal()}</strong>
//         </li>
//       </ul>
//     );
//   }
// }
